# Generated by Django 6.0.3 on 2026-03-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('well_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depth', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('well_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellShow.well')),
            ],
        ),
    ]
