# Generated by Django 6.0.3 on 2026-03-26 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('well_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depth', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timest', models.DateTimeField(auto_now_add=True)),
                ('diff', models.FloatField()),
                ('well_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellShow.well')),
            ],
        ),
    ]
