# Generated by Django 6.0.3 on 2026-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellShow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='well_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
