# Generated by Django 6.0.3 on 2026-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellShow', '0003_well_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
