# Generated by Django 6.0.3 on 2026-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellShow', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='well_id_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
