# Generated by Django 6.0.3 on 2026-03-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellShow', '0006_event_well_id_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='radius',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
