# Generated by Django 6.0.3 on 2026-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellShow', '0007_well_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='well',
            name='critical_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='device_id',
            field=models.CharField(default=1, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
