# Generated by Django 6.0.3 on 2026-04-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellShow', '0008_well_alert_sent_well_critical_level_well_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='well_id_value',
        ),
        migrations.AddField(
            model_name='event',
            name='device_id_value',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
